#!/bin/sh
pgrep -fx "/usr/sbin/VBoxClient --clipboard" > /dev/null
if [ $? -ne 0 ] ; then
    /usr/sbin/VBoxClient --clipboard
fi
pgrep -fx "/usr/sbin/VBoxClient --draganddrop" > /dev/null
if [ $? -ne 0 ] ; then
    /usr/sbin/VBoxClient --draganddrop
fi
pgrep -fx "/usr/sbin/VBoxClient --vmsvga" > /dev/null
if [ $? -ne 0 ] ; then
    /usr/sbin/VBoxClient --vmsvga
fi
